twig:
    file_name_pattern: '*.twig'
    globals:
        # Rejestrujemy zmienną globalną 'contact_api_url'
        contact_api_url: '%env(CONTACT_API_URL)%'

when@test:
    twig:
        strict_variables: true
